---
exclude_paths:
- tests/
- node_modules/
- languages/
- vendor/
- bower_components/
- js/vendor/
- ".sass-cache/"
- "*.min.css"
- "*.min.js"
- "**.css"

prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.scss-lint-r-2.x.yml"
    path: ".scss-lint.yml"
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintrc"
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintignore"
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/markdown.rb"

engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: eslint-3
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: false
  phpmd:
    enabled: false
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.md"
  - "**.js"
  - "**.css"
  - "**.scss"
